# Generated by Django 3.1.6 on 2021-02-13 23:51

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('type', models.TextField(verbose_name='Promo Type')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Promo Code')),
                ('start_time', models.DateTimeField(verbose_name='Promo Start Time')),
                ('end_time', models.DateTimeField(verbose_name='Promo End Time')),
                ('amount', models.FloatField(verbose_name='Promo Amount')),
                ('description', models.TextField(verbose_name='Promo Description')),
                ('status', models.TextField(choices=[('active', 'active'), ('on_hold', 'on_hold')], default='active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
